# the services listed below must be built ON EACH MACHINE that is supposed to participate in the swarm and replicate them
# some services can only be built if the service base_robot has been built
# the following services SHOULD ONLY BE BUILT IF NEEDED on a given machine:
# - db
# - adminer
# - backend
# - three_d_server
# - terrain_server
# - tileserver
# - backend
# - frontend
# building all services at once can take a few minutes
# db, three_d_server, terrain_server, and tileserver depend on local data

# build base_robot FIRST with `sudo docker compose build base_robot`
# build all services with `sudo docker compose build`
# alternatively build one or a select few, i.e. `sudo docker compose build db adminer backend`

# at later stages of the SolarSwarm project, it might be worth to host a registry to manage images (and their versions) more easily 
#   https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-registry/
#   https://www.docker.com/blog/how-to-use-your-own-registry-2/
#   https://docs.docker.com/reference/cli/docker/image/push/
#   https://docs.docker.com/reference/cli/docker/compose/push/

# test locally with `sudo docker compose run`
# to run in a swarm, see 'docker-stack.yaml'
# see locally running services/containers with `sudo docker ps`

services:
  base_robot:
    image: base_robot
    build:
      context: .
      dockerfile: base_robot/base_robot.Dockerfile
      # network: host
    volumes:
      - ./tmp/iw_dump/:/home/ubuntu/iw_dump/
      - ./logs/:/home/ubuntu/logs/
    networks:
      - internal # temporary for testing
    environment:
      - MESH_IP=${MESH_IP}
      - HOST_MAC=${HOST_MAC}
  
  data_sink:
    image: data_sink
    build:
      context: .
      dockerfile: data_sink/sw_robot.Dockerfile
      # network: host
    volumes:
      - ./logs/:/home/ubuntu/logs/
    networks:
      - internal
    environment:
      # data sink
      LOG_OUT: /home/ubuntu/logs/data_sink.log
      FORWARD_TO_DB: forward
      TRIES_TO_GET_STATES: 2
      # DB
      DB_NAME: rosData
      DB_USER: postgres
      DB_PASSWORD: securepassword
      DB_HOST: db
      DB_PORT: "5432"
  
  db:
    image: db
    build:
      context: .
      dockerfile: backend/db.Dockerfile
    environment:
      POSTGRES_DB: rosData
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432" # sonst auf 5433
      - "5173:5173"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer: # to view tables and edit db -> access via localhost:8080 in browser and use db login credentials above
    image: adminer
    container_name: adminer
    restart: 'no'
    ports:
      - 8080:8080
    networks:
      - internal
    depends_on:
      - db

  backend:
    image: backend
    build: 
      context: .
      dockerfile: backend/backend.Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:securepassword@db:5432/rosData
      ROS_DISTRO: jazzy
    ports:
      - "8000:8000"
    networks:
      - internal

  fibonacci_example:
      image: fibonacci_example
      build:
        context: .
        dockerfile: example_ros2_services/example_ros2_services.Dockerfile
      environment:
        - EXAMPLE_ROS2_SERVICE=fibonacci
    
  get_service_server_mac_example:
    image: get_service_server_mac_example
    build:
      context: .
      dockerfile: example_ros2_services/example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=get_service_server_mac

  int_avg_example:
    image: int_avg_example
    build:
      context: .
      dockerfile: example_ros2_services/example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=int_avg

  int_rng_example:
    image: int_rng_example
    build:
      context: .
      dockerfile: example_ros2_services/example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=int_rng

  str_to_lower_upper_example:
    image: str_to_lower_upper_example
    build:
      context: .
      dockerfile: example_ros2_services/example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=str_to_lower_upper

  ### 3D - Meshes on Map ###
  # Deutschland – Zero – Version 2.0
  # https://www.govdata.de/dl-de/zero-2-0
  three_d_server:
    image: three_d_server
    build:
      context: ./backend/backend/
      dockerfile: terrain_server.Dockerfile
    depends_on:
      - backend
    volumes:
      - ./backend/backend:/app
      - ./bigData/data:/app/data
    command: python -u ./file_server/3DServer.py
    ports:
      - "9005:9005"
    networks:
      - internal

  ### Digital Elevation Model ###
  # © Bundesamt für Kartographie und Geodäsie (BKG), Datenlizenz Deutschland – Namensnennung – Version 2.0
  terrain_server:
    image: terrain_server
    build:
      context: ./backend/backend/
      dockerfile: terrain_server.Dockerfile
    depends_on:
      - backend
    volumes:
      - ./backend/backend:/app
      - ./bigData/dem/tiles:/app/terraindata
    command: python -u file_server/TerrainServer.py
    ports:
      - "9010:9010"
    networks:
      - internal

  ### OpenStreetMap-Data Server ###
  # TODO OSM-License
  tileserver:
    image: tileserver
    build:
      context: ./backend/backend/file_server
      dockerfile: tileserver.Dockerfile
    volumes:
      - ./bigData/osmdata/:/osmdata/
      - ./backend/backend/file_server/osm/tileserver:/tileserver
    ports:
      - "9015:9015"
    command: ["-c", "/tileserver/config.json", "-p", "9015", "--silent"]
    networks:
      - internal

  ### Vue ###
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "5170:5170"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --port 5170 --host
    environment:                   
      - VITE_USE_SIM=true
      # Ports
      - VITE_PORT=9000
      - VITE_MESH_3D_SERVER_PORT=9005
      - VITE_DEM_SERVER_PORT=9010
      - VITE_OSM_SERVER_PORT=9015
      # Edit: Chris' Backend URL
      - DB_URL=postgresql://postgres:securepassword@db:5432/rosData
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    external: false
    driver: bridge
  # external is defined and assigned in 'docker-stack.yaml'
  # internal is also redefined in 'docker-stack.yaml' as stacks do not allow bridge networks
  # both files should be merged when deploying the stack