# docker stack delpoy does not build images
# https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-registry/
# https://www.docker.com/blog/how-to-use-your-own-registry-2/
# https://docs.docker.com/reference/cli/docker/image/push/
# docker compose build
# docker compose push: https://docs.docker.com/reference/cli/docker/compose/push/
# run with `sudo docker stack delpoy -c docker-compose.yaml Solarswarm`

services:
  base_robot:
    build:
      context: ./base_robot
      dockerfile: base_robot.Dockerfile
      network: host
    volumes:
      - /tmp/iw_dump/:/tmp/iw_dump/
      - ./logs/:/tmp/logs/
    deploy:
      mode: global
      max_replicas_per_node: 1
      #placement:
        #constraint:
          #- node.labels.<Label> [== <Wert> | != <Wert>]
  
  data_sink:
    build:
      context: ./data_sink
      dockerfile: sw_robot.Dockerfile
      # network: host
    volumes:
      - ./logs/:/tmp/logs/
    networks:
      - internal
    environment:
      # data sink
      # FORWARD_TO_DB: forward
      TRIES_TO_GET_STATES: 2
      # DB
      DB_NAME: rosData
      DB_USER: postgres
      DB_PASSWORD: securepassword
      DB_HOST: db
      DB_PORT: "5432"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraint:
          - node.labels.is_data_sink # should only be given once (same host which runs web and db)
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: rosData
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5173:5173"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:securepassword@db:5432/rosData
      ROS_DISTRO: jazzy
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    # FÃ¼r Development mit Auto-Reload
    command: >
      bash -lc "
        source /opt/ros/jazzy/setup.bash && 
        cd /app && 
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    #network_mode: host
  
  fibonacci_example:
    build:
      context: ./example_ros2_services
      dockerfile: example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=fibonacci
    deploy:
      mode: replicated
      replicas: 2
      max_replicas_per_node: 1
      placement:
        constraint:
          - node.labels.ram_ge_8gb
  
  get_service_server_mac_example:
    build:
      context: ./example_ros2_services
      dockerfile: example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=get_service_server_mac
    deploy:
      mode: global
  
  int_avg_example:
    build:
      context: ./example_ros2_services
      dockerfile: example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=int_avg
    deploy:
      mode: replicated
      replicas: 2
      max_replicas_per_node: 1
      placement:
        constraint:
          - node.labels.ram_ge_8gb
  
  int_rng_example:
    build:
      context: ./example_ros2_services
      dockerfile: example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=int_rng
    deploy:
      mode: replicated
      replicas: 2
      max_replicas_per_node: 1
      placement:
        constraint:
          - node.labels.ram_ge_8gb

  str_to_lower_upper_example:
    build:
      context: ./example_ros2_services
      dockerfile: example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=str_to_lower_upper
    deploy:
      mode: replicated
      replicas: 2
      max_replicas_per_node: 1
      placement:
        constraint:
          - node.labels.ram_ge_8gb

volumes:
  pgdata:

networks:
  internal:
    driver: bridge