# docker stack delpoy does not build images
# https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-registry/
# https://www.docker.com/blog/how-to-use-your-own-registry-2/
# https://docs.docker.com/reference/cli/docker/image/push/
# docker compose build
# docker compose push: https://docs.docker.com/reference/cli/docker/compose/push/
# run with `sudo docker stack delpoy -c docker-compose.yaml Solarswarm`

services:
  base_robot:
    # should run on all robots
    # to excluse nodes from this, change those nodes' availability to drain
    # or introduce a new label and constraints to differentiate between robot and non-robot
    image: base_robot
    build:
      context: .
      dockerfile: base_robot/base_robot.Dockerfile
      # network: host
    volumes:
      - /tmp/iw_dump/:/tmp/iw_dump/
      - ./logs/:/tmp/logs/
    networks:
      - external
  
  data_sink:
    image: data_sink
    build:
      context: .
      dockerfile: data_sink/sw_robot.Dockerfile
      # network: host
    volumes:
      - ./logs/:/tmp/logs/
    networks:
      - internal
      - external
    environment:
      # data sink
      # FORWARD_TO_DB: forward
      TRIES_TO_GET_STATES: 2
      # DB
      DB_NAME: rosData
      DB_USER: postgres
      DB_PASSWORD: securepassword
      DB_HOST: db
      DB_PORT: "5432"
  
  db:
    image: db
    build:
      context: .
      dockerfile: backend/db.Dockerfile
    environment:
      POSTGRES_DB: rosData
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5173:5173"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal


  backend:
    image: backend
    build: 
      context: .
      dockerfile: backend/backend.Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:securepassword@db:5432/rosData
      ROS_DISTRO: jazzy
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/backend:/app
      - ./logs/:/tmp/logs/
    # Für Development mit Auto-Reload
    command: >
      bash -lc "
        source /opt/ros/jazzy/setup.bash && 
        cd /app && 
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    networks:
      - internal
      - external
  
  fibonacci_example:
    image: fibonacci_example
    build:
      context: ./example_ros2_services
      dockerfile: example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=fibonacci
    networks:
      - external
  
  get_service_server_mac_example:
    image: get_service_server_mac_example
    build:
      context: ./example_ros2_services
      dockerfile: example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=get_service_server_mac
    networks:
      - external
  
  int_avg_example:
    image: int_avg_example
    build:
      context: ./example_ros2_services
      dockerfile: example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=int_avg
    networks:
      - external
  
  int_rng_example:
    image: int_rng_example
    build:
      context: ./example_ros2_services
      dockerfile: example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=int_rng
    networks:
      - external

  str_to_lower_upper_example:
    image: str_to_lower_upper_example
    build:
      context: ./example_ros2_services
      dockerfile: example_ros2_services.Dockerfile
    environment:
      - EXAMPLE_ROS2_SERVICE=str_to_lower_upper
    networks:
      - external

  ### 3D - Meshes on Map ###
  # Deutschland – Zero – Version 2.0
  # https://www.govdata.de/dl-de/zero-2-0
  three_d_server:
    image: three_d_server
    build:
      context: ./backend/backend/
      dockerfile: terrain_server.Dockerfile
    depends_on:
      - backend
    volumes:
      - ./backend/backend:/app
      - ./bigData/data:/app/data
    command: python -u ./file_server/3DServer.py
    ports:
      - "9005:9005"
    networks:
      - external

  ### Digital Elevation Model ###
  # © Bundesamt für Kartographie und Geodäsie (BKG), Datenlizenz Deutschland – Namensnennung – Version 2.0
  terrain_server:
    image: terrain_server
    build:
      context: ./backend/backend/
      dockerfile: terrain_server.Dockerfile
    depends_on:
      - backend
    volumes:
      - ./backend/backend:/app
      - ./bigData/dem/tiles:/app/terraindata
    command: python -u file_server/TerrainServer.py
    ports:
      - "9010:9010"
    networks:
      - external

  ### OpenStreetMap-Data Server ###
  # TODO OSM-License
  tileserver:
    image: tileserver
    build:
      context: ./backend/backend/file_server
      dockerfile: tileserver.Dockerfile
    volumes:
      - ./bigData/osm/:/osmdata/
      - ./backend/backend/file_server/osm/tileserver:/tileserver
    ports:
      - "9015:9015"
    command: ["-c", "/tileserver/config.json", "-p", "9015"]
    networks:
      - external

  ### Vue ###
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "5170:5170"
    volumes:
      - ./frontend:/app
    command: npm run dev -- --port 5170 --host
    environment:                   
      - VITE_USE_SIM=true
      # Ports
      - VITE_PORT=9000
      - VITE_MESH_3D_SERVER_PORT=9005
      - VITE_DEM_SERVER_PORT=9010
      - VITE_OSM_SERVER_PORT=9015
      # Edit: Chris' Backend URL
      - DB_URL=http://localhost:XXXX/
    networks:
      - internal
      - external

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
  external:
    driver: overlay